import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SmartChat, { Locale, LocaleContext } from "./components/SmartChat";
import LocaleSwitcher from "./components/LocaleSwitcher";
import React, { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [locale, setLocale] = useState("en");
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white dark:bg-gray-950`}>
        <LocaleSwitcher locale={locale} onChange={setLocale} />
        <LocaleContext.Provider value={locale as Locale}>
          <Navbar />
          <div className="pt-20 min-h-screen flex flex-col">{children}</div>
          <Footer />
          <SmartChat />
        </LocaleContext.Provider>
      </body>
    </html>
  );
}
